# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_auto_20171126_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('identification', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('is_customer', models.BooleanField()),
                ('is_provider', models.BooleanField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Company')),
            ],
        ),
    ]
